server:
    port: 80
spring:
    batch:
      job:
          enabled: true
      jdbc:
          initialize-schema: always
    profiles:
        active: local
    datasource:
        hikari:
            maximum-pool-size: 50
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://127.0.0.1:3306/forum
        username: forum
        password: forum
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                show_sql: true
                format_sql: true
#                use_sql_comments: true

logging:
    level:
        com.zaxxer.hikari.HikariConfig: DEBUG
        com.zaxxer.hikari: DEBUG
